# Generated by Django 6.1 on 2026-08-08 09:20

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_uploadedfile_user_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=base.models.user_upload_path),
        ),
    ]
