# Generated by Django 6.1.1 on 2026-09-22 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_urllink_user_youtbelink_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataFiles',
        ),
    ]
